### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mausch** [streamroot/avro-compat#1]
Hi and thanks for this wrapper!

This is not an issue, just to let you and anyone else landing on this project know I've wrapped your wrapper in a script+Dockerfile for easier use : https://gist.github.com/mausch/c69962e8c5a1462e181224e852761259

Feel free to use that Dockerfile as reference if you ever want to publish it to docker hub or whatever!

**Comment by lerouxrgd** [comment]
Hi, thank you for the Dockerfile!

Note that you can also get the already built jar:
https://github.com/streamroot/avro-compat/releases/download/1.3/avro-compat-1.3.jar

I'll close this since, as you mention, it is not an issue per se.
